### ISSUE TITLE
Add ability to include launch configuration as output

### ISSUE THREAD

**Issue by jozik** [emews/emews-lazybones-templates#1]
The current swift_run_sweep.sh is quite convenient to use, but the launch configuration, e.g., PPN, EXPID, etc., isn't saved anywhere in the TURBINE_OUTPUT directory. It would be helpful to retain the current convenience while still generating the launch config that was used to launch an experiment. Something like what Swift/T already does with:
- turbine.log
- submit.txt
- turbine-slurm.sh

Look into those files one could potentially recreate the launch config, but it might be easiest to actually have a launch config that could be re-used directly.

**Comment by ncollier** [comment]
Added some bash functions to a etc/emews_utils script to log variables and the launch script to the experiment directory.
